import { useCallback, useState } from 'react';
import { RefreshCw, X } from 'lucide-react';
import { getAudit } from '../services/api';
import type { AuditRecord, Decision } from '../services/api';
import { Badge, Empty, ErrorState, Loading, Result } from './shared';
import { decisions } from '../services/presentation';
import { useResource } from '../services/useResource';

export default function AuditLog({ revision }: { revision: number }) {
  const [filter, setFilter] = useState<Decision | ''>(''); const [offset, setOffset] = useState(0);
  const [selected, setSelected] = useState<AuditRecord | null>(null); const [retry, setRetry] = useState(0);
  const load = useCallback(() => getAudit(offset, filter), [offset, filter]);
  const { data: page, error } = useResource(load, `${filter}-${offset}-${revision}-${retry}`);
  return <><section className="panel"><div className="panel-heading"><div><h2>Decision history</h2><p className="muted">Durable evidence from the backend audit log.</p></div><button className="secondary" onClick={() => { setSelected(null); setRetry(v => v + 1); }}><RefreshCw size={15} /> Refresh</button></div><div className="audit-toolbar"><label htmlFor="decision-filter">Filter by decision</label><select id="decision-filter" value={filter} onChange={e => { setFilter(e.target.value as Decision | ''); setOffset(0); setSelected(null); }}><option value="">All decisions</option>{decisions.map(d => <option key={d}>{d}</option>)}</select><span className="muted">{page ? `${page.total.toLocaleString()} records` : 'Fetching records…'}</span></div>{error ? <ErrorState message={error} retry={() => setRetry(v => v + 1)} /> : !page ? <Loading /> : !page.items.length ? <Empty title="No matching audit records">Run a scenario or select another decision filter.</Empty> : <div className="table-wrap"><table><thead><tr><th>Agent / action</th><th>Decision</th><th>Risk</th><th>Recorded</th><th>Evidence</th></tr></thead><tbody>{page.items.map(row => <tr key={row.action_id}><td><strong>{row.action.agent_name}</strong><small>{row.action.proposed_action}</small></td><td><Badge decision={row.result.decision} /></td><td>{row.result.risk_score}/100<small>{row.result.risk_level}</small></td><td>{new Date(row.created_at).toLocaleString()}</td><td><button className="text-button" onClick={() => setSelected(row)} aria-label={`Inspect ${row.action.agent_name} assessment ${row.action_id}`}>Inspect</button></td></tr>)}</tbody></table></div>}<div className="pagination"><button className="secondary" disabled={!page || offset === 0} onClick={() => { setOffset(v => Math.max(0, v - 20)); setSelected(null); }}>Previous</button><span>{page && page.total ? `${Math.min(offset + 1, page.total)}–${Math.min(offset + 20, page.total)} of ${page.total}` : '0 records'}</span><button className="secondary" disabled={!page || offset + 20 >= page.total} onClick={() => { setOffset(v => v + 20); setSelected(null); }}>Next</button></div><p className="footnote">Raw source content, task text, destinations, and resource names are excluded from stored audit records.</p></section>{selected && <div className="audit-detail"><div className="detail-heading"><h2>Selected assessment</h2><button className="secondary" onClick={() => setSelected(null)}><X size={15} />Close</button></div><Result result={selected.result} /></div>}</>;
}
